name: Convert Notebooks

on: [push]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Jupyter Notebooks to Markdown
      uses: MohamedElashri/Jupyter-to-Markdown@ae4c56d0a7094b0ba30d7a1a03014391117b9720

    - name: Commit and push generated markdown
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
